cursor #f1dfd9
cursor_text_color #dcc1b7

foreground            #f1dfd9
background            #1a110e
selection_foreground  #4c2616
selection_background  #f6b9a1
url_color             #ffb598

color0   #1a110e
color1   #ff7772
color2   #97ff7f
color3   #ffe572
color4   #f29d7c
color5   #da7549
color6   #ffb598
color7   #fff4ef
color8   #47413e
color9   #ffa29f
color10  #b6ffa5
color11  #ffeea5
color12  #ffc0a7
color13  #ffcbb6
color14  #ffddd0
color15  #fffaf8
