cursor #e6e2dd
cursor_text_color #ccc6b9

foreground            #e6e2dd
background            #141311
selection_foreground  #343024
selection_background  #cdc6b5
url_color             #fef1cc

color0   #141311
color1   #ff7f72
color2   #91fe7f
color3   #ffe772
color4   #f1e2b8
color5   #e1d5b1
color6   #fef1cc
color7   #fffbef
color8   #44423b
color9   #ffa79f
color10  #b2ffa5
color11  #fff0a5
color12  #fff3d4
color13  #fff5db
color14  #fff9e8
color15  #fffdf8
